regex:
  time:
    1: '/[0-9]{0,2}[:]?[0-9]{1,2}[.][0-9]{2}/'  # 01:35.22
    2: '/[0-9]{1}:?[0-9]{2}\,[0-9]{2}/'         # 1:35,22
    3: '/([0-9]:)?[0-9]{2}\.[0-9]{2}/'          # 1:35.22 | 35.22
    4: '/[0-9]{0,2}[:]?[0-9]{1,2}[:][0-9]{2}/'  # 01:35:22
    5: '/[0-9]{2}:?[0-9]{2}\,[0-9]{2}/'         # 01:35,22
    6: '/(?<=\s)([0-9]:)?[0-9]{2}\.[0-9]{2}/'   # 1:35.22
  name:
    1: >
        /([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?(?!DQ)(?!XDQ))/u
    2: >
        /([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}])([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]\s?)+/u
    3: >
        /(?!.*DSQ|DIS|DNS|dis)\b([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}])([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]\s?)+/u
    4: >
        /(([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’]\s?)+(,?\s?))+/u
    5: >
        /(?!.*DSQ|DIS|DNS|dis)\b([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{2,}\s?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{2,}\s?(?!DQ)(?!XDQ))/u
  first_name:
    1: >
      {02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?(?!DQ)(?!XDQ))/u
  last_name:
    1: >
      {02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?)+(,\s?)([A-z\x{00C0}-\x{02A0}\x{0390}-\x{0520}\-\'\’\.]{1,}\s?(?!DQ)(?!XDQ))/u
  yob:
    1: '/\s[0-9]{2}\s/'         # 96
    2: '/\s[0-9]{4}\s/'         # 1996
    3: '/\s[0-9],[0-9]{3}\s/'   # 1,996
event_signifiers: # if a line contains one of these, the line should contain an event
  - 'Programmanr'
  - 'Event'
  - 'Heat '
event_designifiers: # if a line contains one of these, the line shouldn't contain an event
  - 'DISKWALIFICATIE CODES'
  - 'Leaving the water after an event before permission is given by the official.'
  - 'Not completing the event in accordance with the event description or general rules.'
  - 'Team Rankings'
  - 'Age Name Team Finals Time'
  - 'Name TeamFinals Time'
event_rejectors: # if a line contains one of these, the complete event should be ignored
  - 'Relay'
  - 'Team'
  - 'LC Meter Brick Carry'
  - '35 LC Meter Manikin Carry'
event_stopper: # if a line contains one of these, the current event should be completed and following results are not added
  - 'Open Age Group - Full Results'
round_signifiers:
  - 'Final'
dq_signifiers:
  - 'DQ'
  - '10:00.00'
  - '5:00.00'
  - 'DNF'
  - 'DSQ'
  - 'DIS'
  - 'Forfait'
  - '00:00,00'
  - '88:88.88'
dns_signifiers:
  - 'DNS'
result_rejectors: # if a line contains one of these, the result should be ignored
  - 'Splash Meet Manager'
  - 'Record'
  - 'Australian:'
  - 'World:'
  - 'rekord'
  - 'NR:'
  - 'CR:'
  - 'NR ('
  - 'CR ('
  - 'NR('
  - 'CR('
genders:
  male_signifiers:
    - 'Men'
    - 'Heren'
    - 'Boys'
    - 'Jongens'
    - 'Masculino'
    - 'Male'
  female_signifiers:
    - 'Women'
    - 'Dames'
    - 'Meisjes'
    - 'Femenino'
    - 'Female'
disciplines:
  1:
    - '100m manikin carry with fins'
    - '100m Manikin Carry with Fins'
    - '100m popduiken met zwemvliezen'
    - '100 m. remolque de maniquí'
    - '100m manikin (ring) carry with fins'
    - '100 m Manikin Carry with Fins'
    - '100m mannequin palmes'
    - '100 manikin carry with fins'
    - 'A2-Popredden met vinnen'
    - '100m Popredden met vinnen'
    - '100 LC Metre Fins Manikin Carry'
    - '100 LC Meter Manikin Rescue'
    - '100 LC Meter Manikin Carr'
    - '100 LC Meter manikin carry'
    - '100 LC Meter Manikin Carry'
    - 'Manikin Carry w/Fins'
    - '100 Meter manikin  carry+fins'
    - '100 Meter manikin carry+fins'
    - '100 LC Meter Manakin Carry (Fins)'
    - '100m Manikin Carry'
    - 'Manikin Carry with Fins (100 m)'
  2:
    - '50m manikin carry'
    - '50m Manikin Carry'
    - '50m popduiken'
    - '50 m. remolque de maniquí'
    - '50m Mannequin'
    - '50 manikin carry'
    - 'A4-Popredden'
    - '50m Popredden'
    - '50 LC Metre Manikin Carry'
    - '50 LC Meter Manikin Rescue'
    - '50 LC Meter Manikin Carr'
    - '50 LC Meter mankin carry'
    - '50 Meter mankin carry'
    - '50 LC Meter Manakin Carry'
    - '50m Manikin Carry'
    - '50 M Manikin Carry'
    - 'Manikin Carry (50 m)'
  3:
    - '200m obstacle swim'
    - '200m Obstacle Swim'
    - '200m hinderniszwemmen'
    - '200 m. natación con obstáculos'
    - '200 m Obstacle Swim'
    - '200m Obstacles'
    - 'A1-Hinderniszwemmen'
    - '200 LC Metre Obstacle'
    - '200 LC Metre Masters Obstacle'
    - '200 LC Meter Obstacle'
    - '200 LC Meter Obstacles'
    - '200 LC Meter 0bstacles'
    - '200 Meter Obstacle'
    - '200 m. natación con obstáculos'
    - '200 Obstacle Swim'
  4:
    - '100m manikin tow with fins'
    - '100m lifesaver'
    - '100 m. socorrista'
    - '100 m Manikin Tow with Fins'
    - '100 manikin tow with fins'
    - '100m Manikin Tow with Fins'
    - 'A5-Lifesaver'
    - '100 LC Metre Fins Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 LC Meter Manikin Tow'
    - '100 Meter manikin  tow  +fins'
    - '100 Meter manikin  tow+fins'
    - '100 Meter manikin tow +fins'
    - '100 Meter manikin tow+fins'
    - '100 LC Meter Manakin Tow (Fins)'
    - '100 m. socorrista / manikin tube with fins'
    - '100m Manikin Tow w. Fins'
    - '100m Manikin Tow'
    - 'Manikin Tow with Fins (100 m)'
  5:
    - '100m rescue medley'
    - '100m Rescue Medley'
    - '100m reddingswisselslag'
    - '100 m. combinada de salvamento'
    - '100 m Rescue Medley'
    - '100m Combiné'
    - 'A3-Reddingscombiné'
    - '100m Reddingscombiné'
    - '100 LC Metre Rescue Medley'
    - '100 LC Meter Rescue Medley'
    - '100 LC Meter Rescue Medle'
    - '100 LC Meter Rescue Medley'
    - '100 LC Meter LIFESAVING MEDLEY'
    - '100m Rescuemedley'
    - '100 Rescue medley'
    - '100m Medley'
    - 'Rescue Medley (100 m)'
  6:
    - '200m Super Lifesaver'
    - '200m superlifesaver'
    - '200 m. supersocorrista'
    - '200m super lifesaver'
    - '200 m Super Lifesaver'
    - 'A6-Super Lifesaver'
    - '200 LC Metre Super Lifesaver'
    - '200 LC Meter Super Lifesaver'
    - '200 LC Meter Su'
    - '200 Meter superlifesaver'
    - 'LC Meter Super Life Saver Individual'
    - '200 SLS'
    - '200m Pool Lifesaver'
    - 'Super Lifesaver (200 m) '
  7:
    - '50 m obstacle swim'
    - '50m Obstacle Swim'
  8:
    - '50 m free style'
    - '50m vrije slag'
  9:
    - '50 m freestyle with fins'
    - '50m Freestyle with Fins'
    - '50 LC Meter Swim with Fins'
  10:
    - '50m Manikin Carry (relay leg 3)'
    - '50m popvervoeren (start met pop)'
  11:
    - '50 m slepen torpedo en drenkeling'
  12:
    - '25 m pop'
    - '25m Manikin Carry'
    - '25m pop'
  13:
    - '50 m vrij met torpedo'
    - '50m torpedoboei'
  14:
    - '50 m pop met vliezen'
    - '50m Manikin Carry with Fins (relay leg 4)'
    - '50 m pop  met vliezen'
  18:
    - '100m Obstacle Swim'
    - '100 Meter Obstacle'
    - '100 LC Meter Obstacle'
    - '100 LC Meter Obstacles'
    - '100m Obstacle'
    - '100 Obstacle Swim'
    - '100m Obstacles'
    - '100 m. natación con obstáculos / 100 m. obstacles'
    - 'A1-100m Hinderniszwemmen/Obstacles'